Organizr/Controllers/IdeasController.cs
using Organizr.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Organizr.Controllers
{
   [Authorize]
    public class IdeasController : Controller
    {
        OrganizrContext context;

        public IdeasController()
        {
            context = new OrganizrContext();
        }

        //
        // GET: /Ideas/
        public ActionResult Index()
        {
            return View(context.Ideas.Include("Submitter").ToArray());
        }

        public ActionResult Create()
        {
            return View();
        }

       public ActionResult Details(int id)
       {
           var idea = context.Ideas.Include("Submitter").SingleOrDefault(i => i.Id == id);
           if (idea == null)
           {
               TempData["InfoMessage"] = "This idea does not exists yet... Do you want to create a new one?";
               return RedirectToAction("Create");
           };
            return View(idea);
        }

        [HttpPost]
        public ActionResult Create(Idea idea)
        {
            var currentUser = context.Users.Single(u => u.UserName.Equals(User.Identity.Name));
            context.Ideas.Add(idea);
            idea.Submitter = currentUser;
            idea.Submitted = DateTime.Now;
            if (!ModelState.IsValid)
            {
                return View(idea);
            }
            else
            {
                context.SaveChanges();
                return RedirectToAction("Details", new {id = idea.Id});
            }
            
        }
	}
}

Organizr/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - The Xcellent Ideas</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("The Xcellent Ideas", "Index", "Home", null, new { @class = "brand" })
                <div class="nav-collapse collapse">
                    <ul class="nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        <li>@Html.ActionLink("Find some ideas", "Index", "Ideas")</li>
                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div>
    </div>
    <div class="container">
@if (TempData["InfoMessage"] != null)
{
  <div class="info">
    @TempData["InfoMessage"]
  </div>
}
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>